language: android
env:
  - ANDROID_TARGET=android-15 USE_SQLITE_BINDINGS=false ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default)
  - ANDROID_TARGET=android-16 USE_SQLITE_BINDINGS=true ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default)
  - ANDROID_TARGET=android-16 USE_SQLITE_BINDINGS=false ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default)
  - ANDROID_TARGET=android-19 USE_SQLITE_BINDINGS=true ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default)
  - ANDROID_TARGET=android-19 USE_SQLITE_BINDINGS=false ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default)
android:
  components:
    - build-tools-22.0.1
    - android-15
    - sys-img-armeabi-v7a-android-15
    - android-16
    - sys-img-armeabi-v7a-android-16
    - android-19
    - sys-img-armeabi-v7a-android-19
before_script:
    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
    - ./gradlew squidb-tests:installDebug squidb-tests:installDebugAndroidTest
script:
    - adb shell am instrument -w -e use_sqlite_bindings $USE_SQLITE_BINDINGS com.yahoo.squidb.test/com.yahoo.squidb.test.SquidInstrumentationTestRunner
