/*
 * Copyright 2015, Yahoo Inc.
 * Copyrights licensed under the Apache 2.0 License.
 * See the accompanying LICENSE file for terms.
 */
package com.yahoo.squidb.sql;

import javax.annotation.Nonnull;

/**
 * A SQL statement that can be compiled into a {@link CompiledStatement}
 */
public interface SqlStatement {

    Object[] EMPTY_ARGS = new Object[0];

    /** Suggested initial capacity for StringBuilders when compiling SQL statements */
    int STRING_BUILDER_INITIAL_CAPACITY = 256;

    /** Character substituted by values when used in SQL statements */
    String REPLACEABLE_PARAMETER = "?";
    String REPLACEABLE_ARRAY_PARAMETER = "[?]";
    String REPLACEABLE_ARRAY_PARAMETER_REGEX = "\\[\\?\\]";

    /**
     * Maximum number of variables in a SQLite statement
     */
    int MAX_VARIABLE_NUMBER = 999;

    /**
     * Compile this object into a SQL string and its arguments.
     *
     * @return a {@link CompiledStatement} generated from this object
     */
    @Nonnull
    CompiledStatement compile(@Nonnull CompileContext compileContext);

    /**
     * @return the raw SQL string generated by this object
     */
    @Nonnull
    String toRawSql(@Nonnull CompileContext compileContext);
}
